language: generic

services:
  - docker

before_install:
  - docker pull luksamuk/emacs-export
  - docker ps -a
  
script:
  - make
  - rm -rfv !("docs")
  - mv docs/* ./
  - rm -r docs

deploy:
  provider: pages
  token: $GITHUB_TOKEN
  on:
    branch: master

