language: generic

services:
  - docker

before_install:
  - docker pull luksamuk/emacs-export
  - docker ps -a
  
script:
  - make

deploy:
  provider: pages
  token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: develop
  target-branch: master
 
