language: generic

services:
  - docker

before_install:
  - docker pull luksamuk/emacs-export
  - docker ps -a
  
script:
  - make

deploy:
  provider: pages
  token: $GITHUB_TOKEN
  local_dir: docs
  on:
    branch: master

