language: generic
services:
  - docker

before_install:
  - docker pull luksamuk/emacs-export
  - docker ps -a
  
script:
  - docker run -it --rm -v "$PWD":/root/app luksamuk/emacs-export sh app/ci-run.sh

deploy:
  provider: pages
  token: $github_token
  on:
    branch: master
 
