#+TITLE:          ComputaГ§ГЈo em Diferentes Formas
#+AUTHOR:         Lucas S. Vieira
#+EMAIL:          lucasvieira at protonmail dot com
#+DATE:           Novembro de 2019
#+LANGUAGE:       pt_BR
#+REVEAL_THEME:   serif
#+REVEAL_PLUGINS: (print-pdf zoom)
#+REVEAL_MARGIN:  0.2
#+REVEAL_TRANS:   linear
#+OPTIONS: num:nil timestamp:nil toc:nil
# #+REVEAL_ROOT:    ../../reveal.js
# #+OPTIONS: reveal_single_file:t
#+STARTUP: latexpreview showall inlineimages

#+REVEAL_TITLE_SLIDE: <h3>%t<br/><br/>%a</h3><br/>%d</p>

* IntroduГ§ГЈo

#+REVEAL: split

ProgramaГ§ГЈo Г© uma ГЎrea muito ampla, subdividida em paradigmas.

#+ATTR_REVEAL: :frag (appear)
Paradigmas nos induzem a raciocinar de maneiras especГӯficas.

#+ATTR_REVEAL: :frag (appear)
Mas paradigmas nГЈo sГЈo dissociГЎveis.

#+REVEAL: split

Precisamos de uma mente aberta ao racionalizar a computaГ§ГЈo.

#+ATTR_REVEAL: :frag (appear)
A computaГ§ГЈo realizada nГЈo muda, mas o vocabulГЎrio pode tornar o
processo rГЎpido.

#+ATTR_REVEAL: :frag (appear)
Linguagens especГӯficas sГЈo a ferramenta certa para o propГіsito certo.

#+REVEAL: split

MatemГЎtica constitui uma /linguagem formal/ (ainda que nГЈo seja
universal), onde parte-se de princГӯpios auto-evidentes e,
sob meios de racionalizaГ§ГЈo, chega-se a novas conclusГөes.

#+ATTR_REVEAL: :frag (appear)
\begin{equation*}
        \text{axiomas } \overset{\text{regras de inferГӘncia}}{\longmapsto} \text{ teoremas}
\end{equation*}

#+ATTR_REVEAL: :frag (appear)
"Mathematical notation provides perhaps the best-known and
best-developed example of language used consciously as a tool of
thought." (Iverson, 1986)

#+REVEAL: split

A /notaГ§ГЈo formal/ usada em TC Г© uma linguagem matemГЎtica que especifica
precisamente o funcionamento de mГЎquinas abstratas.

#+ATTR_REVEAL: :frag (appear)
Segundo Iverson (1986), linguagens de programaГ§ГЈo sГЈo notaГ§Гөes formais
universalizadas.

#+REVEAL: split

Mostraremos como /linguagens especГӯficas/ induzem formas diferentes de
pensar ao resolvermos problemas especГӯficos.

#+ATTR_REVEAL: :frag (appear)
Mas primeiro...

* AutГҙmatos celulares unidimensionais

#+REVEAL: split

NotaГ§ГЈo definida por Stephen Wolfram (2002)

Dados gerais de um AC unidimensional:

#+ATTR_REVEAL: :frag (appear)
- Dois estados por cГ©lula: /viva/ (=вӢ„=) ou /morta/ (=.=);
- Dois vizinhos: (esquerdo e direito);
- VizinhanГ§a: TrГӘs cГ©lulas (esquerdo, atual, direito).

** Rule 90

Considere a seguinte regra baseada na vizinhanГ§a:

#+ATTR_HTML: :style font-size:0.7em;
#+begin_example
   вӢ„вӢ„вӢ„   вӢ„вӢ„.   вӢ„.вӢ„   вӢ„..   .вӢ„вӢ„   .вӢ„.   ..вӢ„   ...
    .     вӢ„     .     вӢ„     вӢ„     .     вӢ„     . 
#+end_example

*** Transformando em binГЎrio

#+ATTR_HTML: :style font-size:0.7em;
#+begin_example
          111 110 101 100 011 010 001 000
           0   1   0   1   1   0   1   0
#+end_example

*** Por que "Rule 90"?

\begin{align*}
        01011010_{2} &= (2^{6} + 2^{4} + 2^{3} + 2^{1})\\
                     &= (64_{10} + 16_{10} + 8_{10} + 2_{10})&\\
                     &= 90_{10}
\end{align*}

*** SimplificaГ§ГЈo da regra

Equivale a realizar uma operaГ§ГЈo de /ou-exclusivo/ entre os vizinhos e
ignorar o estado da cГ©lula atual.

#+ATTR_HTML: :style font-size:0.7em;
#+begin_example
                  1X1 1X0 0X1 0X0
                   0   1   1   0 
#+end_example

* APL

#+REVEAL: split

ComeГ§aremos com a linguagem criada por Kenneth E. Iverson, chamada
APL.

#+ATTR_REVEAL: :frag (appear)
APL Г© uma linguagem criada para facilitar a manipulaГ§ГЈo de vetores e
matrizes.

#+ATTR_REVEAL: :frag (appear)
APL nГЈo possui, por padrГЈo, nenhum /condicional/ ou /laГ§o de repetiГ§ГЈo/
explГӯcitos.

** COMMENT AritmГ©tica bГЎsica

#+begin_example
      1+2
3
      3Г—4
12
      3Г·4
0.75
#+end_example

** COMMENT AritmГ©tica com vetores

#+begin_example
      2 5 3-1
1 4 2
      ВҜ1+2 5 3
1 4 2
#+end_example

#+REVEAL: split

#+begin_example
      1 2 3+4 5 6
5 7 9
      1 2+3 4 5
LENGTH ERROR: Mismatched left and right argument shapes
      1 2+3 4 5
         вҲ§
#+end_example

#+REVEAL: split

#+begin_example
      4+3+2
9
      +/4 3 2
9
#+end_example

** COMMENT RotaГ§ГЈo horizontal

#+begin_example
      1вҢҪ4 3 2
3 2 4
      ВҜ1вҢҪ4 3 2
2 4 3
#+end_example

** COMMENT Iota e Reshape

#+begin_example
      вҚі4
1 2 3 4
      2 2вҚҙвҚі4
1 2
3 4
      вҚі9
1 2 3 4 5 6 7 8 9
      3 3вҚҙвҚі9
1 2 3
4 5 6
7 8 9
#+end_example

** COMMENT Implementando a Rule 90

*** Dados para testes

#+begin_example
      вҚі7
1 2 3 4 5 6 7
      (вҚі7)вҲҠ3 4 5
0 0 1 1 1 0 0
      rвҶҗ(вҚі7)вҲҠ3 4 5
#+end_example

*** Calculando nГәmero de vizinhos

#+begin_example
      r r
 0 0 1 1 1 0 0  0 0 1 1 1 0 0 
      ]display r r
в”ҢвҶ’в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”җ
в”Ӯ в”ҢвҶ’в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”җ в”ҢвҶ’в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”җ в”Ӯ
в”Ӯ в”Ӯ0 0 1 1 1 0 0в”Ӯ в”Ӯ0 0 1 1 1 0 0в”Ӯ в”Ӯ
в”Ӯ в””~в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҳ в””~в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҳ в”Ӯ
в””вҲҠв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҳ
      )copy dfns disp
/opt/mdyalog/17.1/64/unicode/ws/dfns.dws saved...
      disp r r
в”Ңв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”¬в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”җ
в”Ӯ0 0 1 1 1 0 0в”Ӯ0 0 1 1 1 0 0в”Ӯ
в””в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҙв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҳ
#+end_example

#+REVEAL: split

#+begin_example
      disp ВҜ1 1вҢҪВЁr r
в”Ңв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”¬в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”җ
в”Ӯ0 0 0 1 1 1 0в”Ӯ0 1 1 1 0 0 0в”Ӯ
в””в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҙв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҳ
      disp ВҜ1 1вҢҪВЁвҠӮr
в”Ңв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”¬в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”җ
в”Ӯ0 0 0 1 1 1 0в”Ӯ0 1 1 1 0 0 0в”Ӯ
в””в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҙв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҳ
#+end_example

#+REVEAL: split

#+begin_example
      disp +/ВҜ1 1вҢҪВЁвҠӮr
в”Ңв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”җ
в”Ӯ0 1 1 2 1 1 0в”Ӯ
в””в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҳ
      disp вҠӮr
в”Ңв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”җ
в”Ӯ0 0 1 1 1 0 0в”Ӯ
в””в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҳ
#+end_example

*** Filtrando as cГ©lulas vivas

#+begin_example
      disp 1=+/ВҜ1 1вҢҪВЁвҠӮr
в”Ңв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”җ
в”Ӯ0 1 1 0 1 1 0в”Ӯ
в””в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҳ
      disp вҠғ1=+/ВҜ1 1вҢҪВЁвҠӮr
0 1 1 0 1 1 0
#+end_example

** FunГ§ГЈo para a Rule 90 em APL

#+ATTR_REVEAL: :frag (appear)
#+begin_src dyalog
rule90вҶҗ{вҠғ1=+/ВҜ1 1вҢҪВЁвҠӮвҚө}
#+end_src

#+ATTR_REVEAL: :frag (appear)
- NГЈo hГЎ nenhuma referГӘncia ao tamanho do vetor;
- NГЈo hГЎ laГ§os de repetiГ§ГЈo explГӯcitos;
- NГЈo hГЎ estruturas de controle de fluxo explГӯcitas.

** DemonstraГ§ГЈo

#+begin_example
      disp 3 1вҚҙr (rule90 r) (rule90 rule90 r)
в”Ңв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”җ
в”Ӯ0 0 1 1 1 0 0в”Ӯ
в”ңв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Ө
в”Ӯ0 1 1 0 1 1 0в”Ӯ
в”ңв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Ө
в”Ӯ1 1 1 0 1 1 1в”Ӯ
в””в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҳ
#+end_example

#+REVEAL: split

#+begin_example
      genвҶҗ{(rule90вҚЈвҚә)вҚө}
      plotgenвҶҗ{rвҶҗвҚөвӢ„(вҠғ,/вҚә (вҚҙr))вҚҙвҠғ,/{вҚө gen r}ВЁВҜ1+вҚівҚә}
      5 plotgen r
0 0 1 1 1 0 0
0 1 1 0 1 1 0
1 1 1 0 1 1 1
0 0 1 0 1 0 0
0 1 0 0 0 1 0
#+end_example

*** VisualizaГ§ГЈo grГЎfica

#+begin_example
      drawfigвҶҗ{' вӢ„'[1+вҚө]}
      ]display drawfig 10 plotgen r
в”ҢвҶ’в”Җв”Җв”Җв”Җв”Җв”Җв”җ
вҶ“  вӢ„вӢ„вӢ„  в”Ӯ
в”Ӯ вӢ„вӢ„ вӢ„вӢ„ в”Ӯ
в”ӮвӢ„вӢ„вӢ„ вӢ„вӢ„вӢ„в”Ӯ
в”Ӯ  вӢ„ вӢ„  в”Ӯ
в”Ӯ вӢ„   вӢ„ в”Ӯ
в”ӮвӢ„ вӢ„ вӢ„ вӢ„в”Ӯ
в”ӮвӢ„     вӢ„в”Ӯ
в”ӮвӢ„вӢ„   вӢ„вӢ„в”Ӯ
в”Ӯ вӢ„вӢ„ вӢ„вӢ„ в”Ӯ
в”ӮвӢ„вӢ„вӢ„ вӢ„вӢ„вӢ„в”Ӯ
в””в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҳ
#+end_example

#+REVEAL: split

#+begin_src dyalog
      ]display drawfig 32 plotgen 31=вҚі61
в”ҢвҶ’в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”җ
вҶ“                              вӢ„                              в”Ӯ
в”Ӯ                             вӢ„ вӢ„                             в”Ӯ
в”Ӯ                            вӢ„   вӢ„                            в”Ӯ
в”Ӯ                           вӢ„ вӢ„ вӢ„ вӢ„                           в”Ӯ
в”Ӯ                          вӢ„       вӢ„                          в”Ӯ
в”Ӯ                         вӢ„ вӢ„     вӢ„ вӢ„                         в”Ӯ
в”Ӯ                        вӢ„   вӢ„   вӢ„   вӢ„                        в”Ӯ
в”Ӯ                       вӢ„ вӢ„ вӢ„ вӢ„ вӢ„ вӢ„ вӢ„ вӢ„                       в”Ӯ
в”Ӯ                      вӢ„               вӢ„                      в”Ӯ
в”Ӯ                     вӢ„ вӢ„             вӢ„ вӢ„                     в”Ӯ
в”Ӯ                    вӢ„   вӢ„           вӢ„   вӢ„                    в”Ӯ
в”Ӯ                   вӢ„ вӢ„ вӢ„ вӢ„         вӢ„ вӢ„ вӢ„ вӢ„                   в”Ӯ
в”Ӯ                  вӢ„       вӢ„       вӢ„       вӢ„                  в”Ӯ
в”Ӯ                 вӢ„ вӢ„     вӢ„ вӢ„     вӢ„ вӢ„     вӢ„ вӢ„                 в”Ӯ
в”Ӯ                вӢ„   вӢ„   вӢ„   вӢ„   вӢ„   вӢ„   вӢ„   вӢ„                в”Ӯ
в”Ӯ               вӢ„ вӢ„ вӢ„ вӢ„ вӢ„ вӢ„ вӢ„ вӢ„ вӢ„ вӢ„ вӢ„ вӢ„ вӢ„ вӢ„ вӢ„ вӢ„               в”Ӯ
в”Ӯ              вӢ„                               вӢ„              в”Ӯ
в”Ӯ             вӢ„ вӢ„                             вӢ„ вӢ„             в”Ӯ
в”Ӯ            вӢ„   вӢ„                           вӢ„   вӢ„            в”Ӯ
в”Ӯ           вӢ„ вӢ„ вӢ„ вӢ„                         вӢ„ вӢ„ вӢ„ вӢ„           в”Ӯ
в”Ӯ          вӢ„       вӢ„                       вӢ„       вӢ„          в”Ӯ
в”Ӯ         вӢ„ вӢ„     вӢ„ вӢ„                     вӢ„ вӢ„     вӢ„ вӢ„         в”Ӯ
в”Ӯ        вӢ„   вӢ„   вӢ„   вӢ„                   вӢ„   вӢ„   вӢ„   вӢ„        в”Ӯ
в”Ӯ       вӢ„ вӢ„ вӢ„ вӢ„ вӢ„ вӢ„ вӢ„ вӢ„                 вӢ„ вӢ„ вӢ„ вӢ„ вӢ„ вӢ„ вӢ„ вӢ„       в”Ӯ
в”Ӯ      вӢ„               вӢ„               вӢ„               вӢ„      в”Ӯ
в”Ӯ     вӢ„ вӢ„             вӢ„ вӢ„             вӢ„ вӢ„             вӢ„ вӢ„     в”Ӯ
в”Ӯ    вӢ„   вӢ„           вӢ„   вӢ„           вӢ„   вӢ„           вӢ„   вӢ„    в”Ӯ
в”Ӯ   вӢ„ вӢ„ вӢ„ вӢ„         вӢ„ вӢ„ вӢ„ вӢ„         вӢ„ вӢ„ вӢ„ вӢ„         вӢ„ вӢ„ вӢ„ вӢ„   в”Ӯ
в”Ӯ  вӢ„       вӢ„       вӢ„       вӢ„       вӢ„       вӢ„       вӢ„       вӢ„  в”Ӯ
в”Ӯ вӢ„ вӢ„     вӢ„ вӢ„     вӢ„ вӢ„     вӢ„ вӢ„     вӢ„ вӢ„     вӢ„ вӢ„     вӢ„ вӢ„     вӢ„ вӢ„ в”Ӯ
в”ӮвӢ„   вӢ„   вӢ„   вӢ„   вӢ„   вӢ„   вӢ„   вӢ„   вӢ„   вӢ„   вӢ„   вӢ„   вӢ„   вӢ„   вӢ„   вӢ„в”Ӯ
в”ӮвӢ„вӢ„ вӢ„ вӢ„ вӢ„ вӢ„ вӢ„ вӢ„ вӢ„ вӢ„ вӢ„ вӢ„ вӢ„ вӢ„ вӢ„ вӢ„ вӢ„ вӢ„ вӢ„ вӢ„ вӢ„ вӢ„ вӢ„ вӢ„ вӢ„ вӢ„ вӢ„ вӢ„ вӢ„ вӢ„ вӢ„вӢ„в”Ӯ
в””в”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”Җв”ҳ
#+end_src

** Programa completo

#+begin_src dyalog
 rule90вҶҗ{вҠғ1=+/ВҜ1 1вҢҪВЁвҠӮвҚө}
 genвҶҗ{(rule90вҚЈвҚә)вҚө}
 plotgenвҶҗ{rвҶҗвҚөвӢ„(вҠғ,/вҚә (вҚҙr))вҚҙвҠғ,/{вҚө gen r}ВЁВҜ1+вҚівҚә}
 drawfigвҶҗ{' вӢ„'[1+вҚө]}
#+end_src

* Outras linguagens?

** Common Lisp

#+begin_src lisp :results output
(defun rot (n list)
  (cond ((zerop n) list)
        ((< n 0)
         (rot (+ (length list) n) list))
        (t (append (nthcdr n list)
                   (butlast list
                            (- (length list)
                               n))))))

(defun rule90 (list)
  (let ((left-rot  (rot 1 (copy-list list)))
        (right-rot (rot -1 (copy-list list))))
    (loop for val1 in left-rot
       for val2 in right-rot
       for num = (+ val1 val2)
       collect (if (= num 1) 1 0))))


(defparameter *r*
  (loop for i from 1 to 7
     collect (if (member i '(3 4 5)) 1 0)))

(format t "~a~%~a~%" *r* (rule90 *r*))
#+end_src

#+REVEAL: split
#+RESULTS:
: (0 0 1 1 1 0 0)
: (0 1 1 0 1 1 0)

** C++ moderno

#+begin_src C++ :main no :exports both :flags --std=c++11 :results output :eval no
#include <iostream>
#include <vector>
#include <algorithm>

void
rule90(std::vector<int>& r)
{
    std::vector<int> lrot(r);
    std::vector<int> rrot(r);

    std::rotate(lrot.begin(),  lrot.begin()  + 1, lrot.end());
    std::rotate(rrot.rbegin(), rrot.rbegin() + 1, rrot.rend());

    for(int i = 0; i < lrot.size(); i++) {
        int neighbors = lrot[i] + rrot[i];
        r[i] = (neighbors == 1) ? 1 : 0;
    }
}

void
print_vec(const std::vector<int>& r)
{
    for(int n : r)
        std::cout << n << ' ';
    std::cout << std::endl;
}

int
main(void)
{
    std::vector<int> r;
    for(int i = 1; i <= 7; i++) {
        if(i == 3 || i == 4 || i == 5)
            r.push_back(1);
        else r.push_back(0);
    }
    
    print_vec(r);
    rule90(r);
    print_vec(r);
    return 0;
}
#+end_src

#+REVEAL: split
#+RESULTS:
: 0 0 1 1 1 0 0 
: 0 1 1 0 1 1 0


* Nem tudo que reluz Г© ouro...

#+REVEAL: split

APL Г© boa para vetores e matrizes, mas nГЈo para propГіsito geral*.

#+ATTR_REVEAL: :frag (appear)
APL requer um esquema de teclado prГіprio.

#+ATTR_REVEAL: :frag (appear)
APL tem implementaГ§Гөes muito fragmentadas.

#+REVEAL: split

As melhores partes de APL estГЈo em Dyalog APL, uma implementaГ§ГЈo /paga/
(se usada comercialmente).

#+ATTR_REVEAL: :frag (appear)
Convenhamos, ninguГ©m usa APL.

* ...mas nem tudo que Г© obscuro Г© carvГЈo!

#+REVEAL: split

Aprender uma linguagem completamente diferente aguГ§a sua forma de
pensar.

#+ATTR_REVEAL: :frag (appear)
Usar um paradigma diferente obriga vocГӘ a pensar de forma diferente.

#+ATTR_REVEAL: :frag (appear)
Muitas soluГ§Гөes para problemas envolvem /pensamento lateral/.

* Problema: DГӯgrafos

Encontre todos os caminhos do nГі =a= ao nГі =e=.

#+begin_src dot :file img/graph.svg :cache yes :cmdline -Kneato -Tsvg
digraph G {
	bgcolor="#00000000";
	node [shape=circle style=inviz width=0.01]

	f[pos="0, 0!"];

	a -> b;
	a -> f;
	a -> g;
	b -> c;
	b -> d;
	c -> d;
	c -> e;
	d -> h;
	g -> h;
	h -> e;
	h -> f;
}
#+end_src

#+RESULTS[da872f3f9f0abaab6cb61eaa8cd06be26653c56f]:
[[file:img/graph.svg]]

** SoluГ§ГЈo nГЈo-trivial: Use Prolog!

#+begin_src prolog :results output :cache yes :eval no
:- initialization main.

edge(a, b).
edge(b, d).
edge(d, h).
edge(a, f).
edge(c, d).
edge(h, e).
edge(a, g).
edge(c, e).
edge(h, f).
edge(b, c).
edge(g, h).

path(A, B, [A, B]) :- edge(A, B).

path(A, B, [A | CB]) :- edge(A, C),
			path(C, B, CB).

main :-
    bagof(P, path(a, e, P), L),
    write(L),
    halt.
#+end_src

#+REVEAL: split
#+RESULTS[66c9b9a6037ba3cb78fafda69ef48556255ffccf]:
: [[a,b,d,h,e],[a,b,c,e],[a,b,c,d,h,e],[a,g,h,e]]

[[file:img/graph.svg]]

#+REVEAL: split

Prolog pode ser de grande ajuda quando utilizado com outros paradigmas
de programaГ§ГЈo.

#+ATTR_REVEAL: :frag (appear)
De fato, variaГ§Гөes de Prolog podem ser utilizadas como linguagens para
/bancos de dados relacionais/.

#+ATTR_REVEAL: :frag (appear)
Prolog tambГ©m pode ser fГЎcil e rapidamente implementado em linguagens
como Scheme (Abelson /et al./, 1996; Pellegrini, 2018).

* ConclusГЈo

MatemГЎtica Г© uma linguagem para racionalizaГ§ГЈo, e portanto, um recurso
para modelagem de raciocГӯnio.

#+ATTR_REVEAL: :frag (appear)
NГЈo prenda sua forma de raciocГӯnio a uma Гәnica linguagem.

#+ATTR_REVEAL: :frag (appear)
Aprenda uma nova linguagem de programaГ§ГЈo (especialmente se for
diferente do que vocГӘ usa).

#+ATTR_REVEAL: :frag (appear)
NotaГ§Гөes sГЈo suas amigas. Busque entender o que elas querem lhe
dizer!

* Bibliografia

#+ATTR_HTML: :style font-size:0.7em;text-align:left;
ABELSON, H.; SUSSMAN, G. J.; SUSSMAN, J. *Structure and interpretation
of computer programs.* MIT Press: Cambridge, 1996. ISBN:
978-0-262-51087-5.

#+ATTR_HTML: :style font-size:0.7em;text-align:left;
IVERSON, K. *Notation as a tool of thought.* IBM Thomas J. Watson
Research Center, 1986.

#+ATTR_HTML: :style font-size:0.7em;text-align:left;
HOLM, N. S. *Prolog control in six slides.* Julho de 2019.

#+ATTR_HTML: :style font-size:0.7em;text-align:left;
PELLEGRINI, J. C. *ProgramaГ§ГЈo funcional e concorrente com Scheme.*
Universidade Federal do ABC: Santo AndrГ©, 2018.
