#!/bin/bash
for f in `find src/pages -name "*.org"`; do
    echo "$f";
    
    # Get the directory of the file
    file_dir=$(dirname "$f")
    
    # Check for bindings in order:
    # 1. File-specific: {filename}-bindings.el
    # 2. Directory-level: {directory}/bindings.el
    # 3. Default: src/pages/bindings.el
    if [ -f "${f%%.org}-bindings.el" ]; then
        bindings="${f%%.org}-bindings.el"
    elif [ -f "$file_dir/bindings.el" ]; then
        bindings="$file_dir/bindings.el"
    else
        bindings="./src/pages/bindings.el"
    fi
    
    emacs --batch \
          -l "/root/.emacs.d/init.el" \
          -l "./src/macros.el" \
          -l "$bindings" \
          --kill \
          "$f" \
          -f org-html-export-to-html;
    
    # Get the relative path from src/pages/
    rel_path="${f#src/pages/}"
    rel_dir=$(dirname "$rel_path")
    
    # Create target directory preserving structure
    mkdir -p "docs/pages/$rel_dir"
    
    # Move HTML to correct subdirectory
    mv "${f%%.org}.html" "docs/pages/$rel_dir/";
done

# Copy static assets (preserve structure)
# Copy .cpp files
find src/pages -name "*.cpp" -exec sh -c '
    rel_path="${1#src/pages/}"
    rel_dir=$(dirname "$rel_path")
    mkdir -p "docs/pages/$rel_dir"
    cp "$1" "docs/pages/$rel_dir/"
' _ {} \;

# Copy .svg files (generated by dot/graphviz)
find src/pages -name "*.svg" -exec sh -c '
    rel_path="${1#src/pages/}"
    rel_dir=$(dirname "$rel_path")
    mkdir -p "docs/pages/$rel_dir"
    cp "$1" "docs/pages/$rel_dir/"
' _ {} \;