#+TITLE: [Draft] Big Data e o Demônio de Laplace
#+SETUPFILE: setupfile.org
#+LANGUAGE:  pt_BR
#+AUTHOR:    Lucas Vieira
#+EMAIL:     lucasvieira@protonmail.com
#+DATE:      Out 06, 2019
#+STARTUP:   inlineimages

# Introduzir o assunto

# Talvez colocar algumas coisas do artigo da Santaella
Estive, recentemente, no XII Encontro Brasileiro Internacional de
Ciência Cognitiva (EBICC), que foi extremamente proveitoso. O tema
principal orbitou as implicações do Big Data em diversas disciplinas,
como Ética, Epistemologia, Semiótica, Cognição e Ação.

Neste post, pretendo me conter um pouco ao conceito da Ética para
falar a respeito de uma pequena ideia que tive ao longo das muitas
discussões. No evento de abertura, a professora Lúcia Santaella (PUC -
SP) trouxe uma reflexão extremamente interessante a respeito de alguns
artigos da revista Wired que, quando lançados, foram tidos como
sensacionalistas. [[https://www.wired.com/2008/06/pb-theory/][Um dos artigos]] previa o fim da "Teoria", ou melhor
dizendo, do método científico como é. Para o autor, esta realidade
culmina em uma época de Big Data e Pós-Verdade, onde estabelecer bases
de causação passam a ser irrelevantes quando absolutamente tudo
poderia ser previsto através de correlações.

Meu objetivo neste texto não é repetir o que a professora Santaella
disse, ou também reafirmar o consenso realizado no XII EBICC[fn:1],
mas sim explorar um cenário mental levando em consideração o impacto
que as predições de padrões de usuários, através do uso de Big Data,
podem causar na nossa forma de vida e na nossa maneira de pensar. A
meu ver, há um risco de estarmos fabricando nossos próprios "falsos
deuses" e seguindo-os cegamente. Já explico o que quero dizer.

* Deuses e Demônios

Bem, na verdade, "deuses" é uma palavra forte. O melhor termo para o
que eu imaginei seria "demônio", baseado no conceito do Demônio de
Laplace. Fazendo uma breve pesquisa na [[https://en.wikipedia.org/wiki/Laplace%27s_demon][Wikipedia]], tem-se que este
conceito baseia-se em uma forte pressuposição de /determinismo/ na
realidade, onde se alguém -- o demônio -- souber o local e o momento
exatos de cada átomo no Universo, seus valores passados e futuros
podem ser calculados por leis da Mecânica Clássica. O conceito possui
problemas[fn:2] e pode ser facilmente refutado[fn:3], sendo portanto
uma forma ruim de modelar a realidade.

Mas vamos forçar a barra um pouco. Suponhamos que, mesmo com as
considerações anteriores, fizéssemos o melhor para coletar nossas
informações -- o que não será a totalidade do momento, mas será o que
julgamos ser "suficiente" para representá-lo. Com base nesta situação
do momento /t/, faremos alguns cálculos e, com um pouco de sorte,
chegaremos a uma situação correspondente ao esperado no momento /t+1/.

# Relacionar o demônio de Laplace ao Big Data


# Finalizar

* Footnotes

[fn:3] Aumento da entropia, Interpretação de Copenhagen, Teoria do
Caos e a Diagonalização de Cantor são tópicos utilizados para refutar
o demônio de Laplace. Mais informações podem ser encontradas no artigo
da Wikipedia linkado acima.

[fn:2] Obviamente, se partirmos para a Mecânica Quântica, o próprio
[[https://en.wikipedia.org/wiki/Observer_effect_(physics)][Efeito do Observador]] já coloca em cheque esta possibilidade, ainda que
hipotética, em um sistema fechado. Alie-a ao [[https://en.wikipedia.org/wiki/Uncertainty_principle][Princípio da Incerteza de
Heinsenberg]], que determina a impossibilidade de sabermos, de forma
exata, a localização e o momento de uma partícula, e teremos o último
prego no caixão.

[fn:1] Longe de mim falar por todos os participantes mas, pelo que
percebi, há uma concordância generalizada de que esta realidade não
necessariamente torna o método científico obsoleto, pois ainda há a
necessidade de análise das correlações para estabelecermos hipóteses
que expliquem os fenômenos estudados. Portanto, Big Data é uma
ferramenta cientificamente útil, e não um rompimento com a forma
vigente de se fazer ciência, ainda que isto possa representar uma
mudança na forma como o método científico é aplicado.
