#+TITLE: RASCUNHO LLMs
#+SETUPFILE: setupfile.org
#+LANGUAGE:  pt_BR
#+STARTUP:   inlineimages showall latexpreview
#+DATE:      Fev 01, 2026

Desde o último texto que escrevi  referente a LLMs e inteligência artificial, em
que mostrei  como configurei meu ambiente  para lidar com essas  ferramentas, eu
acabei  mudando  muito  o  meu  ambiente e  inclusive  trocando  de  soluções  e
melhorando meus modelos locais. Ao  mesmo tempo, também fiz muitos experimentos,
tirei algumas conclusões, e estudei algumas coisas sobre o assunto para entender
melhor como tudo isso funciona.

Tem muitos aspectos técnicos nessa questão que  valem MUITO A PENA exporar, e eu
ainda  estou planejando  fazer  mais um  texto  sobre isso  ainda  nesse mês  de
fevereiro, mas  eu resolvi  deixar um pouco  para depois porque  eu vou  ter que
refazer alguns  pequenos experimentos e  também levantar algumas  informações de
forma mais correta.

Hoje eu quero discutir um pouco essas questões  de IA e LLM de um ponto de vista
um pouco filosófico,  e também conjecturar um  pouco a respeito do  que eu penso
que essas soluções  vão representar para nós no futuro.  Acredito que, depois de
passar de  totalmente cético e crítico  ao uso, ter experimentado,  e ter também
tido  uma abordagem  bem  técnica no  assunto, longe  dos  perigos noturnos  dos
marketeiros e dos "AI Bros", posso dar uma opinião educada sobre o assunto.

* A revolução das interfaces

Uma das coisas que acho mais importante no uso de /Large Language Models/ (LLMs) é
a capacidade  que temos de  executá-las localmente.  Existe toda uma  questão de
privacidade e comodidade que vem com isso. e é justamente essa comodidade que me
atrai.

Há um  tempo vi de  relance algum  artigo ou reportagem  dizendo que tudo  o que
sabemos sobre  interfaces e  experiência do  usuário se  tornariam conhecimentos
obsoletos. A ideia era de que as interações com telas, botões e outros elementos
seriam puramente substituídas pela comunicação  em texto e linguagem natural das
IAs (LLMs e outras abstrações como agentes).

Obviamente isso é  balela. Não me oponho particularmente a  isso porque adoro um
terminal, uma interface textual, mas pensar  em substituição é algo extremo, até
porque precisamos  nos lembrar  de que  o próprio ambiente  visual em  que temos
acesso  a  essas IAs  também  deve  passar por  uma  revisão  de experiência  do
usuário. Do  contrário, aí  sim estaríamos  nos comunicando  com IAs  apenas via
console.

# [ imagem do open webui em alguma conversa minha menos relevante ]

Ainda  que as  paredes de  texto das  IAs não  sejam substitutos  para elementos
visuais, cada vez mais empresas vêm integrando suas soluções com agentes capazes
de  realizarem  inferência e  responder  perguntas  baseadas nos  elementos  dos
produtos e  das soluções dessas  empresas. Por  exemplo, a Microsoft  colocou um
botão ou barra  do Copilot em absolutamente tudo  o que podia. E se  você for um
desenvolvedor usando  Visual Studio Code,  você já  deve ter percebido  uma nova
barra lateral que te ajude a operar agentes para fazer o que você quiser.

Essas barras auxiliares,  a meu ver, não são exatamente  muito intuitivas para o
usuário, porque vão na contramão da  intuitividade. Você será forçado a aprender
uma nova  nomenclatura antes de  conseguir utilizar tudo aquilo.  Poucas pessoas
sabem o que é  um agente, RAG, ou qualquer nomenclatura ligada a  IA. E cada dia
surge mais  vocabulário: skills, prompt  do sistema, prompt do  usuário... Seria
inevitável que isso  acontecesse, mas fica evidente como quem  vai resolver esse
tipo de barreira vai ser a UX clássica, mesmo.

Tenho uma preferência  particular pela ideia das barras  de pesquisas integradas
com IA que já vi em certas  documentações, apesar de achar um grande defeito que
a pesquisa via IA seja geralmente  sugerida como primeira sugestão. Pesquisas em
bancos de dados DEMORAM, dependendo do cenário, então já vi sugestões diretas de
enviar um prompt para  uma IA em vez de esperar o retorno  do resultado. Se você
tiver automatizado  a ideia de digitar  uma pesquisa e dar  enter, esperando uma
tela  de carregamento...  já era.  A  pesquisa é  abortada e  abre-se uma  barra
lateral com IA (estou olhando para vocês, documentação do Agno Framework!).

# [ exemplo aqui de documentações, tipo a documentação do Agno ]

Aliás, acho que vale a pena até  apontar para o lado interessante dessa história
de documentação  apoiada por IA: trata-se  TAMBÉM de um tipo  de pesquisa, porém
com o  risco do não-determinismo e  das informações erradas, que  convenhamos, é
elevado. Mas inconsistências  à parte, pesquisar através da IA  só me faz pensar
que *as IAs são basicamente nossos novos controles-remoto*.

** Controles-remotos

Talvez isso pareça uma analogia estranha ou precipitada, mas vou explicar.

Para  que serve  um  controle-remoto  de televisão?  Bem,  olhando  aqui para  o
controle da minha  Smart TV, eu tenho  algumas teclas de todos  os tipos. Teclas
para aumentar ou diminuir o volume. Teclas para trocar o canal (algo que hoje já
não uso mais,  pois não assisto mais  TV). Teclas para deixar o  volume no mudo,
para desligar  a TV... e temos  também teclas de  navegação que têm um  uso mais
abstrato, porque suas funcionalidades variam dependendo do contexto, ou seja, do
aplicativo que estiver sendo manipulado.

Meu controle de Smart  TV tem também outras operações mais  abstratas e até mais
comerciais. Por exemplo, botões de pelo menos quatro serviços de /streaming/. Digo
que são operações mais abstratas porque o  processo de abrir um aplicativo de um
serviço de /streaming/ não necessariamente demanda  um contexto prévio do que você
estava   assistindo,  apenas   demanda  que   a  TV   mude  para   o  aplicativo
requisitado. Isso  requer muitas  nuances do  sistema operacional  da televisão,
porque "trocar um app  por outro" tem todo um significado  dentro do Android TV:
existem  coisas  chamadas   /intents/  e  outras  questões  nas   quais  nunca  me
aprofundei. Mesmo  assim, são formas  abstratas de  um serviço referenciar  e se
comunicar com outro aplicativo.

O  que quero  dizer com  tudo isso  é  que existe  um mecanismo  de operação  /da
interface/  para essas  funcionalidades, sejam  elas mais  ou menos  abstratas. A
semiótica do processo  deixa bem claro para o usuário  o que cada funcionalidade
faz. Cada função  separada pode ser diretamente ativada, e  o meio para ativação
de cada função  é o usuário saber  exatamente o que quer fazer,  e então decidir
qual botão apertar. Dizendo assim soa óbvio, mas veja o quanto o controle-remoto
demanda que  o usuário tenha  conhecimento de  símbolos, ícones, e  também tenha
automatizado o  que ele quer fazer.  Será que alguém mais  idoso, acostumado com
televisões cujos botões sejam aqueles de  girar, vão saber manipular um controle
com teclas "+" e "-" e um texto "Vol." entre elas?

# Essas ferramentas são como controles-remotos  para opções, só que facilitados,
# através de um processo de inferência  que torne mais orgânico você encontrar a
# informação  que você  procura.  O usuário  tem perguntas  do  mesmo jeito,  só
# estamos  mudando   a  forma  de  responder   e  como  ele  vai   encontrar  as
# funcionalidades.

# Analogia com controles-remotos
# Puxar o gancho do encontro das funcionalidades

** Interfaces na programação

** Interfaces na orientação a objetos de Alan Kay

* LLMs como interfaces de linguagem natural

# Citar a questão das LLMs rodadas localmente  e citar a questão de que o modelo
# de hoje de execução em cloud não se sustenta

# Citar também a  questão do hype do clawde/moltbot/openclaw, etc,  e por que as
# pessoas adoraram  esse negócio  -- interface. "Alexa,  só que  funciona". Ouvi
# isso muito

* Pontos de evolução

# Citar a questão da inferência como diferencial
# Citar a questão da limitação do contexto
# Mencionar a  questão do modelo mental  da psicologia de memória  de trabalho e
# etc

* Prospectos

# Inferência está tendo resultados extremamente promissores, citar o caso do GLM
# 4.7 Flash

# Contexto ainda está sendo um gargalo

# Relembrar  a questão  do uso  pessoal de  LLMs porque  o modelo  atual não  se
# sustenta, a meu ver

# Modelos devem ser cada vez mais  eficientes para serem executados localmente e
# com menos recursos
