name: Deploy to GitHub Pages
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Build:
    runs-on: ubuntu-latest
    container:
      image: luksamuk/emacs-export
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build stuff
        run: sh ./ci-run.sh

      - name: Deploy to GH Pages
        uses: JamesIves/github-pages-deploy-action@v4.6.5
        with:
          branch: gh-pages
          folder: docs

