name: Deploy to GitHub Pages
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Build:
    runs-on: ubuntu-latest
    container:
      image: luksamuk/emacs-export

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build stuff
        run: sh ./ci-run.sh

      - name: Check status
        run: ls

      - name: Check src
        run: ls src/

      - name: Deploy to GH Pages
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: docs

